language: node_js
sudo: false
node_js:
  - 8

cache:
  yarn: true
  directories:
    - .eslintcache
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

after_install:
  - yarn run clean
  - yarn run build

script:
  - yarn lint
  - yarn test
